In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

# Load the dataset
df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

# Define the target variable
target = 'Attrition'
df[target] = df[target].map({'Yes': 1, 'No': 0})  # Convert to binary: 1 for Yes, 0 for No

# Features as specified
numerical_features = [
    'Age', 'DailyRate', 'DistanceFromHome', 'EnvironmentSatisfaction',
    'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
    'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
    'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
    'YearsWithCurrManager'
]

categorical_features = [
    'BusinessTravel', 'Department', 'EducationField', 'JobRole',
    'MaritalStatus', 'OverTime'
]

# Select features and target
X = df[numerical_features + categorical_features]
y = df[target]

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),  # Numerical features as is
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)  # One-hot encode categoricals
    ]
)

# Create the pipeline with Random Forest Classifier
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]  # Probability of Attrition=Yes (1)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# Bin probabilities into Low, Medium, High risk
bins = [0, 0.33, 0.66, 1.0]
labels = ['Low', 'Medium', 'High']
risk_levels = pd.cut(y_prob, bins=bins, labels=labels, include_lowest=True)

# Example: Print some predictions with risk levels
results = pd.DataFrame({
    'Actual': y_test,
    'Predicted': y_pred,
    'Probability': y_prob,
    'Risk Level': risk_levels
})
print("\nSample Predictions:\n", results.head(10))

Accuracy: 0.8741496598639455
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.98      0.93       255
           1       0.60      0.15      0.24        39

    accuracy                           0.87       294
   macro avg       0.74      0.57      0.59       294
weighted avg       0.85      0.87      0.84       294


Sample Predictions:
       Actual  Predicted  Probability Risk Level
1041       0          0         0.13        Low
184        0          0         0.06        Low
1222       1          1         0.53     Medium
67         0          0         0.03        Low
220        0          0         0.06        Low
494        0          1         0.54     Medium
430        0          0         0.16        Low
240        0          0         0.10        Low
218        0          0         0.21        Low
49         0          0         0.18        Low

In [2]:
df.sample()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
626,32,0,Travel_Rarely,638,Research & Development,8,2,Medical,1,865,...,3,80,1,9,3,2,5,3,1,3

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

# Load the dataset
df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

# Define the target variable
target = 'Attrition'
df[target] = df[target].map({'Yes': 1, 'No': 0})  # Convert to binary: 1 for Yes, 0 for No

# Features as specified
numerical_features = [
    'Age', 'DailyRate', 'DistanceFromHome', 'EnvironmentSatisfaction',
    'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
    'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
    'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
    'YearsWithCurrManager'
]

categorical_features = [
    'BusinessTravel', 'Department', 'EducationField', 'JobRole',
    'MaritalStatus', 'OverTime'
]

# Select features and target
X = df[numerical_features + categorical_features]
y = df[target]

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),  # Numerical features as is
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)  # One-hot encode categoricals
    ]
)

# Create the pipeline with Random Forest Classifier
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]  # Probability of Attrition=Yes (1)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# Bin probabilities into Low, Medium, High risk
bins = [0, 0.33, 0.66, 1.0]
labels = ['Low', 'Medium', 'High']
risk_levels = pd.cut(y_prob, bins=bins, labels=labels, include_lowest=True)

# Example: Print some predictions with risk levels, including feature values
results = pd.concat([X_test.reset_index(drop=True), pd.DataFrame({
    'Actual': y_test.reset_index(drop=True),
    'Predicted': y_pred,
    'Probability': y_prob,
    'Risk Level': risk_levels
})], axis=1)
print("\nSample Predictions:\n", results.head(10))

Accuracy: 0.8741496598639455
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.98      0.93       255
           1       0.60      0.15      0.24        39

    accuracy                           0.87       294
   macro avg       0.74      0.57      0.59       294
weighted avg       0.85      0.87      0.84       294


Sample Predictions:
    Age  DailyRate  DistanceFromHome  EnvironmentSatisfaction  JobInvolvement  \
0   28        866                 5                        4               3
1   53       1084                13                        4               4
2   24        240                22                        4               1
3   45       1339                 7                        2               3
4   36       1396                 5                        4               3
5   34        204                14                        3               3
6   35        144                22                        4               1
7   39       1431                 1                        3               3
8   45       1052                 6                        4               2
9   35       1229                 8                        4               4

   JobLevel  JobSatisfaction  MonthlyIncome  StockOptionLevel  \
0         2                1           8463                 0
1         2                1           4450                 2
2         1                3           1555                 1
3         3                1           9724                 1
4         2                2           5914                 0
5         1                3           2579                 2
6         1                3           4230                 0
7         1                3           2232                 3
8         3                4           8865                 0
9         1                4           2269                 0

   TotalWorkingYears  ...  BusinessTravel              Department  \
0                  6  ...   Travel_Rarely                   Sales
1                  5  ...   Travel_Rarely  Research & Development
2                  1  ...   Travel_Rarely         Human Resources
3                 25  ...   Travel_Rarely  Research & Development
4                 16  ...   Travel_Rarely  Research & Development
5                  8  ...   Travel_Rarely                   Sales
6                  6  ...   Travel_Rarely  Research & Development
7                  7  ...   Travel_Rarely  Research & Development
8                 23  ...      Non-Travel                   Sales
9                  1  ...   Travel_Rarely  Research & Development

     EducationField                 JobRole  MaritalStatus OverTime Actual  \
0           Medical         Sales Executive         Single       No      0
1           Medical  Manufacturing Director       Divorced       No      0
2   Human Resources         Human Resources        Married       No      1
3     Life Sciences      Research Scientist       Divorced       No      0
4     Life Sciences   Laboratory Technician         Single       No      0
5  Technical Degree    Sales Representative       Divorced      Yes      0
6     Life Sciences   Laboratory Technician         Single       No      0
7           Medical   Laboratory Technician       Divorced       No      0
8           Medical         Sales Executive         Single       No      0
9     Life Sciences   Laboratory Technician        Married       No      0

  Predicted Probability Risk Level
0         0        0.13        Low
1         0        0.06        Low
2         1        0.53     Medium
3         0        0.03        Low
4         0        0.06        Low
5         1        0.54     Medium
6         0        0.16        Low
7         0        0.10        Low
8         0        0.21        Low
9         0        0.18        Low

[10 rows x 25 columns]

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

# Load the dataset
df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

# Define the target variable
target = 'Attrition'
df[target] = df[target].map({'Yes': 1, 'No': 0})  # Convert to binary: 1 for Yes, 0 for No

# Features as specified
numerical_features = [
    'Age', 'DailyRate', 'DistanceFromHome', 'EnvironmentSatisfaction',
    'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
    'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
    'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
    'YearsWithCurrManager'
]

categorical_features = [
    'BusinessTravel', 'Department', 'EducationField', 'JobRole',
    'MaritalStatus', 'OverTime'
]

# Select features and target
X = df[numerical_features + categorical_features]
y = df[target]

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),  # Numerical features as is
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)  # One-hot encode categoricals
    ]
)

# Create the pipeline with Random Forest Classifier
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]  # Probability of Attrition=Yes (1)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# Bin probabilities into Low, Medium, High risk
bins = [0, 0.33, 0.66, 1.0]
labels = ['Low', 'Medium', 'High']
risk_levels = pd.cut(y_prob, bins=bins, labels=labels, include_lowest=True)

# Example: Print some predictions with risk levels, including feature values at the end
results = pd.concat([pd.DataFrame({
    'Actual': y_test.reset_index(drop=True),
    'Predicted': y_pred,
    'Probability': y_prob,
    'Risk Level': risk_levels
}), X_test.reset_index(drop=True)], axis=1)
print("\nSample Predictions:\n", results.head(10))

Accuracy: 0.8741496598639455
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.98      0.93       255
           1       0.60      0.15      0.24        39

    accuracy                           0.87       294
   macro avg       0.74      0.57      0.59       294
weighted avg       0.85      0.87      0.84       294


Sample Predictions:
    Actual  Predicted  Probability Risk Level  Age  DailyRate  \
0       0          0         0.13        Low   28        866
1       0          0         0.06        Low   53       1084
2       1          1         0.53     Medium   24        240
3       0          0         0.03        Low   45       1339
4       0          0         0.06        Low   36       1396
5       0          1         0.54     Medium   34        204
6       0          0         0.16        Low   35        144
7       0          0         0.10        Low   39       1431
8       0          0         0.21        Low   45       1052
9       0          0         0.18        Low   35       1229

   DistanceFromHome  EnvironmentSatisfaction  JobInvolvement  JobLevel  ...  \
0                 5                        4               3         2  ...
1                13                        4               4         2  ...
2                22                        4               1         1  ...
3                 7                        2               3         3  ...
4                 5                        4               3         2  ...
5                14                        3               3         1  ...
6                22                        4               1         1  ...
7                 1                        3               3         1  ...
8                 6                        4               2         3  ...
9                 8                        4               4         1  ...

   WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  YearsWithCurrManager  \
0                3               5                   4                     3
1                3               4                   2                     3
2                3               1                   0                     0
3                3               1                   0                     0
4                4              13                  11                     7
5                3               8                   2                     6
6                3               5                   4                     3
7                3               3                   2                     2
8                3              19                   7                     8
9                3               1                   0                     1

   BusinessTravel              Department    EducationField  \
0   Travel_Rarely                   Sales           Medical
1   Travel_Rarely  Research & Development           Medical
2   Travel_Rarely         Human Resources   Human Resources
3   Travel_Rarely  Research & Development     Life Sciences
4   Travel_Rarely  Research & Development     Life Sciences
5   Travel_Rarely                   Sales  Technical Degree
6   Travel_Rarely  Research & Development     Life Sciences
7   Travel_Rarely  Research & Development           Medical
8      Non-Travel                   Sales           Medical
9   Travel_Rarely  Research & Development     Life Sciences

                  JobRole  MaritalStatus OverTime
0         Sales Executive         Single       No
1  Manufacturing Director       Divorced       No
2         Human Resources        Married       No
3      Research Scientist       Divorced       No
4   Laboratory Technician         Single       No
5    Sales Representative       Divorced      Yes
6   Laboratory Technician         Single       No
7   Laboratory Technician       Divorced       No
8         Sales Executive         Single       No
9   Laboratory Technician        Married       No

[10 rows x 25 columns]

In [8]:
X.sample()

,Age,DailyRate,DistanceFromHome,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,StockOptionLevel,TotalWorkingYears,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsWithCurrManager,BusinessTravel,Department,EducationField,JobRole,MaritalStatus,OverTime
1132,40,118,14,4,3,2,1,4639,1,5,...,3,5,4,2,Travel_Rarely,Sales,Life Sciences,Sales Executive,Married,No

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

# Load the dataset
df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

# Define the target variable
target = 'Attrition'
df[target] = df[target].map({'Yes': 1, 'No': 0})  # Convert to binary: 1 for Yes, 0 for No

# Features as specified
numerical_features = [
    'Age', 'DailyRate', 'DistanceFromHome', 'EnvironmentSatisfaction',
    'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
    'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
    'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
    'YearsWithCurrManager'
]

categorical_features = [
    'BusinessTravel', 'Department', 'EducationField', 'JobRole',
    'MaritalStatus', 'OverTime'
]

# Select features and target
X = df[numerical_features + categorical_features]
y = df[target]

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),  # Numerical features as is
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)  # One-hot encode categoricals
    ]
)

# Create the pipeline with Random Forest Classifier
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]  # Probability of Attrition=Yes (1)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# Bin probabilities into Low, Medium, High risk
bins = [0, 0.33, 0.66, 1.0]
labels = ['Low', 'Medium', 'High']
risk_levels = pd.cut(y_prob, bins=bins, labels=labels, include_lowest=True)

# Create the results DataFrame
results = pd.concat([pd.DataFrame({
    'Actual': y_test.reset_index(drop=True),
    'Predicted': y_pred,
    'Probability': y_prob,
    'Risk Level': risk_levels
}), X_test.reset_index(drop=True)], axis=1)

# Define retention strategies with thresholds for key features
# Thresholds are based on typical dataset statistics and attrition risk factors:
# - Numerical: Using approximate medians/quartiles where low/high values increase risk (e.g., low Age < 30, high DistanceFromHome > 10)
# - Categorical: Conditions like OverTime == 'Yes'
strategies = {
    'OverTime': {
        'condition': lambda row: row['OverTime'] == 'Yes',
        'strategy': 'Implement overtime caps, flexible scheduling, and burnout prevention programs to improve work-life balance.'
    },
    'MonthlyIncome': {
        'condition': lambda row: row['MonthlyIncome'] < 5000,  # Below approximate median (~6500)
        'strategy': 'Offer competitive salary reviews, bonuses, or financial wellness programs to address compensation concerns.'
    },
    'Age': {
        'condition': lambda row: row['Age'] < 30,  # Younger employees often at higher risk
        'strategy': 'Provide mentorship, career development paths, and intergenerational team-building for younger employees.'
    },
    'TotalWorkingYears': {
        'condition': lambda row: row['TotalWorkingYears'] < 10,  # Less experience linked to higher attrition
        'strategy': 'Introduce loyalty incentives, sabbaticals, or internal rotations to retain mid-career talent.'
    },
    'JobLevel': {
        'condition': lambda row: row['JobLevel'] < 2,  # Entry-level roles at higher risk
        'strategy': 'Establish clear promotion pathways and leadership training for lower-level employees.'
    },
    'YearsAtCompany': {
        'condition': lambda row: row['YearsAtCompany'] < 5,  # Short tenure increases risk
        'strategy': 'Enhance onboarding with check-ins and anniversary perks to improve early retention.'
    },
    'YearsWithCurrManager': {
        'condition': lambda row: row['YearsWithCurrManager'] < 3,  # Instability with manager
        'strategy': 'Train managers in relationship-building and conduct team-building events.'
    },
    'StockOptionLevel': {
        'condition': lambda row: row['StockOptionLevel'] == 0,  # No options linked to lower commitment
        'strategy': 'Expand equity programs and educate on long-term benefits to increase employee investment.'
    },
    'DistanceFromHome': {
        'condition': lambda row: row['DistanceFromHome'] > 10,  # Longer commutes increase risk
        'strategy': 'Support remote/hybrid work options or relocation assistance to reduce commute stress.'
    },
    'JobSatisfaction': {
        'condition': lambda row: row['JobSatisfaction'] < 3,  # Low satisfaction (scale 1-4)
        'strategy': 'Conduct satisfaction surveys and implement recognition programs to boost morale.'
    }
}

# Function to determine strategies for a row
def get_strategies(row):
    suggested = []
    for feature, info in strategies.items():
        if info['condition'](row):
            suggested.append(f"{feature}: {info['strategy']}")
    if not suggested:
        suggested.append("No specific strategies needed based on thresholds.")
    return '; '.join(suggested)

# Add Suggested Strategies column, applying only if Risk Level is Medium or High
results['Suggested_Strategies'] = results.apply(
    lambda row: get_strategies(row) if row['Risk Level'] in ['Medium', 'High'] else 'Low risk - Monitor generally.',
    axis=1
)

# Example: Print some predictions with risk levels and strategies
print("\nSample Predictions with Strategies:\n", results.head(10))

Accuracy: 0.8741496598639455
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.98      0.93       255
           1       0.60      0.15      0.24        39

    accuracy                           0.87       294
   macro avg       0.74      0.57      0.59       294
weighted avg       0.85      0.87      0.84       294


Sample Predictions with Strategies:
    Actual  Predicted  Probability Risk Level  Age  DailyRate  \
0       0          0         0.13        Low   28        866
1       0          0         0.06        Low   53       1084
2       1          1         0.53     Medium   24        240
3       0          0         0.03        Low   45       1339
4       0          0         0.06        Low   36       1396
5       0          1         0.54     Medium   34        204
6       0          0         0.16        Low   35        144
7       0          0         0.10        Low   39       1431
8       0          0         0.21        Low   45       1052
9       0          0         0.18        Low   35       1229

   DistanceFromHome  EnvironmentSatisfaction  JobInvolvement  JobLevel  ...  \
0                 5                        4               3         2  ...
1                13                        4               4         2  ...
2                22                        4               1         1  ...
3                 7                        2               3         3  ...
4                 5                        4               3         2  ...
5                14                        3               3         1  ...
6                22                        4               1         1  ...
7                 1                        3               3         1  ...
8                 6                        4               2         3  ...
9                 8                        4               4         1  ...

   YearsAtCompany  YearsInCurrentRole  YearsWithCurrManager  BusinessTravel  \
0               5                   4                     3   Travel_Rarely
1               4                   2                     3   Travel_Rarely
2               1                   0                     0   Travel_Rarely
3               1                   0                     0   Travel_Rarely
4              13                  11                     7   Travel_Rarely
5               8                   2                     6   Travel_Rarely
6               5                   4                     3   Travel_Rarely
7               3                   2                     2   Travel_Rarely
8              19                   7                     8      Non-Travel
9               1                   0                     1   Travel_Rarely

               Department    EducationField                 JobRole  \
0                   Sales           Medical         Sales Executive
1  Research & Development           Medical  Manufacturing Director
2         Human Resources   Human Resources         Human Resources
3  Research & Development     Life Sciences      Research Scientist
4  Research & Development     Life Sciences   Laboratory Technician
5                   Sales  Technical Degree    Sales Representative
6  Research & Development     Life Sciences   Laboratory Technician
7  Research & Development           Medical   Laboratory Technician
8                   Sales           Medical         Sales Executive
9  Research & Development     Life Sciences   Laboratory Technician

   MaritalStatus  OverTime                               Suggested_Strategies
0         Single        No                      Low risk - Monitor generally.
1       Divorced        No                      Low risk - Monitor generally.
2        Married        No  MonthlyIncome: Offer competitive salary review...
3       Divorced        No                      Low risk - Monitor generally.
4         Single        No                      Low risk - Monitor generally.
5       Divorced       Yes  OverTime: Implement overtime caps, flexible sc...
6         Single        No                      Low risk - Monitor generally.
7       Divorced        No                      Low risk - Monitor generally.
8         Single        No                      Low risk - Monitor generally.
9        Married        No                      Low risk - Monitor generally.

[10 rows x 26 columns]

In [11]:
# Remove the space at the end of 'Suggested_Strategies '
print("\nSample Predictions with Strategies:\n", results.head(10)['Suggested_Strategies'])

Sample Predictions with Strategies:
 0                        Low risk - Monitor generally.
1                        Low risk - Monitor generally.
2    MonthlyIncome: Offer competitive salary review...
3                        Low risk - Monitor generally.
4                        Low risk - Monitor generally.
5    OverTime: Implement overtime caps, flexible sc...
6                        Low risk - Monitor generally.
7                        Low risk - Monitor generally.
8                        Low risk - Monitor generally.
9                        Low risk - Monitor generally.
Name: Suggested_Strategies, dtype: object

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

# Load the dataset
df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

# Define the target variable
target = 'Attrition'
df[target] = df[target].map({'Yes': 1, 'No': 0})  # Convert to binary: 1 for Yes, 0 for No

# Features as specified
numerical_features = [
    'Age', 'DailyRate', 'DistanceFromHome', 'EnvironmentSatisfaction',
    'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
    'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
    'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
    'YearsWithCurrManager'
]

categorical_features = [
    'BusinessTravel', 'Department', 'EducationField', 'JobRole',
    'MaritalStatus', 'OverTime'
]

# Select features and target
X = df[numerical_features + categorical_features]
y = df[target]

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),  # Numerical features as is
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)  # One-hot encode categoricals
    ]
)

# Create the pipeline with Random Forest Classifier
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]  # Probability of Attrition=Yes (1)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# Bin probabilities into Low, Medium, High risk
bins = [0, 0.33, 0.66, 1.0]
labels = ['Low', 'Medium', 'High']
risk_levels = pd.cut(y_prob, bins=bins, labels=labels, include_lowest=True)

# Create the results DataFrame
results = pd.concat([pd.DataFrame({
    'Actual': y_test.reset_index(drop=True),
    'Predicted': y_pred,
    'Probability': y_prob,
    'Risk Level': risk_levels
}), X_test.reset_index(drop=True)], axis=1)

# Define retention strategies with thresholds for key features
# Thresholds are based on typical dataset statistics and attrition risk factors:
# - Numerical: Using approximate medians/quartiles where low/high values increase risk (e.g., low Age < 30, high DistanceFromHome > 10)
# - Categorical: Conditions like OverTime == 'Yes'
strategies = {
    'OverTime': {
        'condition': lambda row: row['OverTime'] == 'Yes',
        'strategy': 'Implement overtime caps, flexible scheduling, and burnout prevention programs to improve work-life balance.'
    },
    'MonthlyIncome': {
        'condition': lambda row: row['MonthlyIncome'] < 5000,  # Below approximate median (~6500)
        'strategy': 'Offer competitive salary reviews, bonuses, or financial wellness programs to address compensation concerns.'
    },
    'Age': {
        'condition': lambda row: row['Age'] < 30,  # Younger employees often at higher risk
        'strategy': 'Provide mentorship, career development paths, and intergenerational team-building for younger employees.'
    },
    'TotalWorkingYears': {
        'condition': lambda row: row['TotalWorkingYears'] < 10,  # Less experience linked to higher attrition
        'strategy': 'Introduce loyalty incentives, sabbaticals, or internal rotations to retain mid-career talent.'
    },
    'JobLevel': {
        'condition': lambda row: row['JobLevel'] < 2,  # Entry-level roles at higher risk
        'strategy': 'Establish clear promotion pathways and leadership training for lower-level employees.'
    },
    'YearsAtCompany': {
        'condition': lambda row: row['YearsAtCompany'] < 5,  # Short tenure increases risk
        'strategy': 'Enhance onboarding with check-ins and anniversary perks to improve early retention.'
    },
    'YearsWithCurrManager': {
        'condition': lambda row: row['YearsWithCurrManager'] < 3,  # Instability with manager
        'strategy': 'Train managers in relationship-building and conduct team-building events.'
    },
    'StockOptionLevel': {
        'condition': lambda row: row['StockOptionLevel'] == 0,  # No options linked to lower commitment
        'strategy': 'Expand equity programs and educate on long-term benefits to increase employee investment.'
    },
    'DistanceFromHome': {
        'condition': lambda row: row['DistanceFromHome'] > 10,  # Longer commutes increase risk
        'strategy': 'Support remote/hybrid work options or relocation assistance to reduce commute stress.'
    },
    'JobSatisfaction': {
        'condition': lambda row: row['JobSatisfaction'] < 3,  # Low satisfaction (scale 1-4)
        'strategy': 'Conduct satisfaction surveys and implement recognition programs to boost morale.'
    }
}

# Function to determine strategies for a row
def get_strategies(row):
    suggested = []
    for feature, info in strategies.items():
        if info['condition'](row):
            suggested.append(f"{feature}: {info['strategy']}")
    if not suggested:
        suggested.append("No specific strategies needed based on thresholds.")
    return '; '.join(suggested)

# Add Suggested Strategies column, applying only if Risk Level is Medium or High
results['Suggested_Strategies'] = results.apply(
    lambda row: get_strategies(row) if row['Risk Level'] in ['Medium', 'High'] else 'Low risk - Monitor generally.',
    axis=1
)

# Example: Print some predictions with risk levels and strategies
print("\nSample Predictions with Strategies:\n", results.head(10))

 # Load the new dataset
new_df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')   # <-- replace with your filename

# Make sure it has the same features as the original dataset
X_new = new_df[numerical_features + categorical_features]

# Predict attrition class (0/1)
new_pred = model.predict(X_new)

# Predict probability of attrition
new_prob = model.predict_proba(X_new)[:, 1]

# Convert probability to risk bins
risk_levels_new = pd.cut(
    new_prob,
    bins=[0, 0.33, 0.66, 1.0],
    labels=['Low', 'Medium', 'High'],
    include_lowest=True
)

# Apply your strategy function
new_df_results = pd.concat([
    pd.DataFrame({
        'Predicted': new_pred,
        'Probability': new_prob,
        'Risk Level': risk_levels_new
    }),
    X_new.reset_index(drop=True)
], axis=1)

# Add strategies
new_df_results['Suggested_Strategies'] = new_df_results.apply(
    lambda row: get_strategies(row) if row['Risk Level'] in ['Medium', 'High']
    else 'Low risk - Monitor generally.',
    axis=1
)
# Save predictions to a CSV file
new_df_results.to_csv('attrition_predictions.csv', index=False)

print("Saved results to attrition_predictions.csv")

print(new_df_results.head())

Accuracy: 0.8741496598639455
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.98      0.93       255
           1       0.60      0.15      0.24        39

    accuracy                           0.87       294
   macro avg       0.74      0.57      0.59       294
weighted avg       0.85      0.87      0.84       294


Sample Predictions with Strategies:
    Actual  Predicted  Probability Risk Level  Age  DailyRate  \
0       0          0         0.13        Low   28        866
1       0          0         0.06        Low   53       1084
2       1          1         0.53     Medium   24        240
3       0          0         0.03        Low   45       1339
4       0          0         0.06        Low   36       1396
5       0          1         0.54     Medium   34        204
6       0          0         0.16        Low   35        144
7       0          0         0.10        Low   39       1431
8       0          0         0.21        Low   45       1052
9       0          0         0.18        Low   35       1229

   DistanceFromHome  EnvironmentSatisfaction  JobInvolvement  JobLevel  ...  \
0                 5                        4               3         2  ...
1                13                        4               4         2  ...
2                22                        4               1         1  ...
3                 7                        2               3         3  ...
4                 5                        4               3         2  ...
5                14                        3               3         1  ...
6                22                        4               1         1  ...
7                 1                        3               3         1  ...
8                 6                        4               2         3  ...
9                 8                        4               4         1  ...

   YearsAtCompany  YearsInCurrentRole  YearsWithCurrManager  BusinessTravel  \
0               5                   4                     3   Travel_Rarely
1               4                   2                     3   Travel_Rarely
2               1                   0                     0   Travel_Rarely
3               1                   0                     0   Travel_Rarely
4              13                  11                     7   Travel_Rarely
5               8                   2                     6   Travel_Rarely
6               5                   4                     3   Travel_Rarely
7               3                   2                     2   Travel_Rarely
8              19                   7                     8      Non-Travel
9               1                   0                     1   Travel_Rarely

               Department    EducationField                 JobRole  \
0                   Sales           Medical         Sales Executive
1  Research & Development           Medical  Manufacturing Director
2         Human Resources   Human Resources         Human Resources
3  Research & Development     Life Sciences      Research Scientist
4  Research & Development     Life Sciences   Laboratory Technician
5                   Sales  Technical Degree    Sales Representative
6  Research & Development     Life Sciences   Laboratory Technician
7  Research & Development           Medical   Laboratory Technician
8                   Sales           Medical         Sales Executive
9  Research & Development     Life Sciences   Laboratory Technician

   MaritalStatus  OverTime                               Suggested_Strategies
0         Single        No                      Low risk - Monitor generally.
1       Divorced        No                      Low risk - Monitor generally.
2        Married        No  MonthlyIncome: Offer competitive salary review...
3       Divorced        No                      Low risk - Monitor generally.
4         Single        No                      Low risk - Monitor generally.
5       Divorced       Yes  OverTime: Implement overtime caps, flexible sc...
6         Single        No                      Low risk - Monitor generally.
7       Divorced        No                      Low risk - Monitor generally.
8         Single        No                      Low risk - Monitor generally.
9        Married        No                      Low risk - Monitor generally.

[10 rows x 26 columns]
Saved results to attrition_predictions.csv
   Predicted  Probability Risk Level  Age  DailyRate  DistanceFromHome  \
0          1         0.78       High   41       1102                 1
1          0         0.00        Low   49        279                 8
2          1         0.83       High   37       1373                 2
3          0         0.17        Low   33       1392                 3
4          0         0.00        Low   27        591                 2

   EnvironmentSatisfaction  JobInvolvement  JobLevel  JobSatisfaction  ...  \
0                        2               3         2                4  ...
1                        3               2         2                2  ...
2                        4               2         1                3  ...
3                        4               3         1                3  ...
4                        1               3         1                2  ...

   YearsAtCompany  YearsInCurrentRole  YearsWithCurrManager  \
0               6                   4                     5
1              10                   7                     7
2               0                   0                     0
3               8                   7                     0
4               2                   2                     2

      BusinessTravel              Department  EducationField  \
0      Travel_Rarely                   Sales   Life Sciences
1  Travel_Frequently  Research & Development   Life Sciences
2      Travel_Rarely  Research & Development           Other
3  Travel_Frequently  Research & Development   Life Sciences
4      Travel_Rarely  Research & Development         Medical

                 JobRole  MaritalStatus OverTime  \
0        Sales Executive         Single      Yes
1     Research Scientist        Married       No
2  Laboratory Technician         Single      Yes
3     Research Scientist        Married      Yes
4  Laboratory Technician        Married       No

                                Suggested_Strategies
0  OverTime: Implement overtime caps, flexible sc...
1                      Low risk - Monitor generally.
2  OverTime: Implement overtime caps, flexible sc...
3                      Low risk - Monitor generally.
4                      Low risk - Monitor generally.

[5 rows x 25 columns]

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

# Load the dataset
df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

# Define the target variable
target = 'Attrition'
df[target] = df[target].map({'Yes': 1, 'No': 0})  # Convert to binary: 1 for Yes, 0 for No

# Features as specified
numerical_features = [
    'Age', 'DailyRate', 'DistanceFromHome', 'EnvironmentSatisfaction',
    'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
    'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
    'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
    'YearsWithCurrManager'
]

categorical_features = [
    'BusinessTravel', 'Department', 'EducationField', 'JobRole',
    'MaritalStatus', 'OverTime'
]

# Select features and target
X = df[numerical_features + categorical_features]
y = df[target]

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),  # Numerical features as is
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)  # One-hot encode categoricals
    ]
)

# Create the pipeline with Random Forest Classifier
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]  # Probability of Attrition=Yes (1)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# Bin probabilities into Low, Medium, High risk
bins = [0, 0.33, 0.66, 1.0]
labels = ['Low', 'Medium', 'High']
risk_levels = pd.cut(y_prob, bins=bins, labels=labels, include_lowest=True)

# Create the results DataFrame
results = pd.concat([pd.DataFrame({
    'Actual': y_test.reset_index(drop=True),
    'Predicted': y_pred,
    'Probability': y_prob,
    'Risk Level': risk_levels
}), X_test.reset_index(drop=True)], axis=1)

# Define retention strategies with thresholds for key features
# Thresholds are based on typical dataset statistics and attrition risk factors:
# - Numerical: Using approximate medians/quartiles where low/high values increase risk (e.g., low Age < 30, high DistanceFromHome > 10)
# - Categorical: Conditions like OverTime == 'Yes'
strategies = {
    'OverTime': {
        'condition': lambda row: row['OverTime'] == 'Yes',
        'strategy': 'Implement overtime caps, flexible scheduling, and burnout prevention programs to improve work-life balance.'
    },
    'MonthlyIncome': {
        'condition': lambda row: row['MonthlyIncome'] < 5000,  # Below approximate median (~6500)
        'strategy': 'Offer competitive salary reviews, bonuses, or financial wellness programs to address compensation concerns.'
    },
    'Age': {
        'condition': lambda row: row['Age'] < 30,  # Younger employees often at higher risk
        'strategy': 'Provide mentorship, career development paths, and intergenerational team-building for younger employees.'
    },
    'TotalWorkingYears': {
        'condition': lambda row: row['TotalWorkingYears'] < 10,  # Less experience linked to higher attrition
        'strategy': 'Introduce loyalty incentives, sabbaticals, or internal rotations to retain mid-career talent.'
    },
    'JobLevel': {
        'condition': lambda row: row['JobLevel'] < 2,  # Entry-level roles at higher risk
        'strategy': 'Establish clear promotion pathways and leadership training for lower-level employees.'
    },
    'YearsAtCompany': {
        'condition': lambda row: row['YearsAtCompany'] < 5,  # Short tenure increases risk
        'strategy': 'Enhance onboarding with check-ins and anniversary perks to improve early retention.'
    },
    'YearsWithCurrManager': {
        'condition': lambda row: row['YearsWithCurrManager'] < 3,  # Instability with manager
        'strategy': 'Train managers in relationship-building and conduct team-building events.'
    },
    'StockOptionLevel': {
        'condition': lambda row: row['StockOptionLevel'] == 0,  # No options linked to lower commitment
        'strategy': 'Expand equity programs and educate on long-term benefits to increase employee investment.'
    },
    'DistanceFromHome': {
        'condition': lambda row: row['DistanceFromHome'] > 10,  # Longer commutes increase risk
        'strategy': 'Support remote/hybrid work options or relocation assistance to reduce commute stress.'
    },
    'JobSatisfaction': {
        'condition': lambda row: row['JobSatisfaction'] < 3,  # Low satisfaction (scale 1-4)
        'strategy': 'Conduct satisfaction surveys and implement recognition programs to boost morale.'
    }
}

# Function to determine strategies for a row
def get_strategies(row):
    suggested = []
    for feature, info in strategies.items():
        if info['condition'](row):
            suggested.append(f"{feature}: {info['strategy']}")
    if not suggested:
        suggested.append("No specific strategies needed based on thresholds.")
    return '; '.join(suggested)

# Add Suggested Strategies column, applying only if Risk Level is Medium or High
results['Suggested_Strategies'] = results.apply(
    lambda row: get_strategies(row) if row['Risk Level'] in ['Medium', 'High'] else 'Low risk - Monitor generally.',
    axis=1
)

# Example: Print some predictions with risk levels and strategies
print("\nSample Predictions with Strategies:\n", results.head(10))

 # Load the new dataset
new_df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')   # <-- replace with your filename

# Make sure it has the same features as the original dataset
X_new = new_df[numerical_features + categorical_features]

# Predict attrition class (0/1)
new_pred = model.predict(X_new)

# Predict probability of attrition
new_prob = model.predict_proba(X_new)[:, 1]

# Convert probability to risk bins
risk_levels_new = pd.cut(
    new_prob,
    bins=[0, 0.33, 0.66, 1.0],
    labels=['Low', 'Medium', 'High'],
    include_lowest=True
)

# Apply your strategy function
# Add a unique ID to the new dataset
new_df['EmployeeID'] = range(1, len(new_df) + 1)  # Simple sequential ID starting from 1

# Make sure features are selected correctly (excluding the new ID for model input)
X_new = new_df[numerical_features + categorical_features]

# Predict
new_pred = model.predict(X_new)
new_prob = model.predict_proba(X_new)[:, 1]

# Bin probabilities into risk levels
risk_levels_new = pd.cut(new_prob, bins=[0, 0.33, 0.66, 1.0],
                         labels=['Low', 'Medium', 'High'], include_lowest=True)

# Combine predictions with features and EmployeeID
new_df_results = pd.concat([
    pd.DataFrame({
        'EmployeeID': new_df['EmployeeID'],
        'Predicted': new_pred,
        'Probability': new_prob,
        'Risk Level': risk_levels_new
    }),
    X_new.reset_index(drop=True)
], axis=1)

# Add suggested strategies
new_df_results['Suggested_Strategies'] = new_df_results.apply(
    lambda row: get_strategies(row) if row['Risk Level'] in ['Medium', 'High']
    else 'Low risk - Monitor generally.',
    axis=1
)

# Save to CSV
new_df_results.to_csv('attrition_predictions_with_ID.csv', index=False)
print("Saved results to attrition_predictions_with_ID.csv")

Accuracy: 0.8741496598639455
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.98      0.93       255
           1       0.60      0.15      0.24        39

    accuracy                           0.87       294
   macro avg       0.74      0.57      0.59       294
weighted avg       0.85      0.87      0.84       294


Sample Predictions with Strategies:
    Actual  Predicted  Probability Risk Level  Age  DailyRate  \
0       0          0         0.13        Low   28        866
1       0          0         0.06        Low   53       1084
2       1          1         0.53     Medium   24        240
3       0          0         0.03        Low   45       1339
4       0          0         0.06        Low   36       1396
5       0          1         0.54     Medium   34        204
6       0          0         0.16        Low   35        144
7       0          0         0.10        Low   39       1431
8       0          0         0.21        Low   45       1052
9       0          0         0.18        Low   35       1229

   DistanceFromHome  EnvironmentSatisfaction  JobInvolvement  JobLevel  ...  \
0                 5                        4               3         2  ...
1                13                        4               4         2  ...
2                22                        4               1         1  ...
3                 7                        2               3         3  ...
4                 5                        4               3         2  ...
5                14                        3               3         1  ...
6                22                        4               1         1  ...
7                 1                        3               3         1  ...
8                 6                        4               2         3  ...
9                 8                        4               4         1  ...

   YearsAtCompany  YearsInCurrentRole  YearsWithCurrManager  BusinessTravel  \
0               5                   4                     3   Travel_Rarely
1               4                   2                     3   Travel_Rarely
2               1                   0                     0   Travel_Rarely
3               1                   0                     0   Travel_Rarely
4              13                  11                     7   Travel_Rarely
5               8                   2                     6   Travel_Rarely
6               5                   4                     3   Travel_Rarely
7               3                   2                     2   Travel_Rarely
8              19                   7                     8      Non-Travel
9               1                   0                     1   Travel_Rarely

               Department    EducationField                 JobRole  \
0                   Sales           Medical         Sales Executive
1  Research & Development           Medical  Manufacturing Director
2         Human Resources   Human Resources         Human Resources
3  Research & Development     Life Sciences      Research Scientist
4  Research & Development     Life Sciences   Laboratory Technician
5                   Sales  Technical Degree    Sales Representative
6  Research & Development     Life Sciences   Laboratory Technician
7  Research & Development           Medical   Laboratory Technician
8                   Sales           Medical         Sales Executive
9  Research & Development     Life Sciences   Laboratory Technician

   MaritalStatus  OverTime                               Suggested_Strategies
0         Single        No                      Low risk - Monitor generally.
1       Divorced        No                      Low risk - Monitor generally.
2        Married        No  MonthlyIncome: Offer competitive salary review...
3       Divorced        No                      Low risk - Monitor generally.
4         Single        No                      Low risk - Monitor generally.
5       Divorced       Yes  OverTime: Implement overtime caps, flexible sc...
6         Single        No                      Low risk - Monitor generally.
7       Divorced        No                      Low risk - Monitor generally.
8         Single        No                      Low risk - Monitor generally.
9        Married        No                      Low risk - Monitor generally.

[10 rows x 26 columns]
Saved results to attrition_predictions_with_ID.csv

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

# Load the dataset
df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

# Define the target variable
target = 'Attrition'
df[target] = df[target].map({'Yes': 1, 'No': 0})  # Convert to binary: 1 for Yes, 0 for No

# Features as specified
numerical_features = [
    'Age', 'DailyRate', 'DistanceFromHome', 'EnvironmentSatisfaction',
    'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
    'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
    'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
    'YearsWithCurrManager'
]

categorical_features = [
    'BusinessTravel', 'Department', 'EducationField', 'JobRole',
    'MaritalStatus', 'OverTime'
]

# Select features and target
X = df[numerical_features + categorical_features]
y = df[target]

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),  # Numerical features as is
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)  # One-hot encode categoricals
    ]
)

# Create the pipeline with Random Forest Classifier
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]  # Probability of Attrition=Yes (1)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# Bin probabilities into Low, Medium, High risk
bins = [0, 0.33, 0.66, 1.0]
labels = ['Low', 'Medium', 'High']
risk_levels = pd.cut(y_prob, bins=bins, labels=labels, include_lowest=True)

# Create the results DataFrame
results = pd.concat([pd.DataFrame({
    'Actual': y_test.reset_index(drop=True),
    'Predicted': y_pred,
    'Probability': y_prob,
    'Risk Level': risk_levels
}), X_test.reset_index(drop=True)], axis=1)

# Define retention strategies with thresholds for key features
# Thresholds are based on typical dataset statistics and attrition risk factors:
# - Numerical: Using approximate medians/quartiles where low/high values increase risk (e.g., low Age < 30, high DistanceFromHome > 10)
# - Categorical: Conditions like OverTime == 'Yes'
strategies = {
    'OverTime': {
        'condition': lambda row: row['OverTime'] == 'Yes',
        'strategy': 'Implement overtime caps, flexible scheduling, and burnout prevention programs to improve work-life balance.'
    },
    'MonthlyIncome': {
        'condition': lambda row: row['MonthlyIncome'] < 5000,  # Below approximate median (~6500)
        'strategy': 'Offer competitive salary reviews, bonuses, or financial wellness programs to address compensation concerns.'
    },
    'Age': {
        'condition': lambda row: row['Age'] < 30,  # Younger employees often at higher risk
        'strategy': 'Provide mentorship, career development paths, and intergenerational team-building for younger employees.'
    },
    'TotalWorkingYears': {
        'condition': lambda row: row['TotalWorkingYears'] < 10,  # Less experience linked to higher attrition
        'strategy': 'Introduce loyalty incentives, sabbaticals, or internal rotations to retain mid-career talent.'
    },
    'JobLevel': {
        'condition': lambda row: row['JobLevel'] < 2,  # Entry-level roles at higher risk
        'strategy': 'Establish clear promotion pathways and leadership training for lower-level employees.'
    },
    'YearsAtCompany': {
        'condition': lambda row: row['YearsAtCompany'] < 5,  # Short tenure increases risk
        'strategy': 'Enhance onboarding with check-ins and anniversary perks to improve early retention.'
    },
    'YearsWithCurrManager': {
        'condition': lambda row: row['YearsWithCurrManager'] < 3,  # Instability with manager
        'strategy': 'Train managers in relationship-building and conduct team-building events.'
    },
    'StockOptionLevel': {
        'condition': lambda row: row['StockOptionLevel'] == 0,  # No options linked to lower commitment
        'strategy': 'Expand equity programs and educate on long-term benefits to increase employee investment.'
    },
    'DistanceFromHome': {
        'condition': lambda row: row['DistanceFromHome'] > 10,  # Longer commutes increase risk
        'strategy': 'Support remote/hybrid work options or relocation assistance to reduce commute stress.'
    },
    'JobSatisfaction': {
        'condition': lambda row: row['JobSatisfaction'] < 3,  # Low satisfaction (scale 1-4)
        'strategy': 'Conduct satisfaction surveys and implement recognition programs to boost morale.'
    }
}

# Function to determine strategies for a row
def get_strategies(row):
    suggested = []
    for feature, info in strategies.items():
        if info['condition'](row):
            suggested.append(f"{feature}: {info['strategy']}")
    if not suggested:
        suggested.append("No specific strategies needed based on thresholds.")
    return '; '.join(suggested)

# Add Suggested Strategies column, applying only if Risk Level is Medium or High
results['Suggested_Strategies'] = results.apply(
    lambda row: get_strategies(row) if row['Risk Level'] in ['Medium', 'High'] else 'Low risk - Monitor generally.',
    axis=1
)

# Example: Print some predictions with risk levels and strategies
print("\nSample Predictions with Strategies:\n", results.head(10))

 # Load the new dataset
new_df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')   # <-- replace with your filename

# Make sure it has the same features as the original dataset
X_new = new_df[numerical_features + categorical_features]

# Predict attrition class (0/1)
new_pred = model.predict(X_new)

# Predict probability of attrition
new_prob = model.predict_proba(X_new)[:, 1]

# Convert probability to risk bins
risk_levels_new = pd.cut(
    new_prob,
    bins=[0, 0.33, 0.66, 1.0],
    labels=['Low', 'Medium', 'High'],
    include_lowest=True
)

# Apply your strategy function
# Add a unique ID to the new dataset
new_df['EmployeeID'] = range(1, len(new_df) + 1)  # Simple sequential ID starting from 1

# Make sure features are selected correctly (excluding the new ID for model input)
X_new = new_df[numerical_features + categorical_features]

# Predict
new_pred = model.predict(X_new)
new_prob = model.predict_proba(X_new)[:, 1]

# Bin probabilities into risk levels
risk_levels_new = pd.cut(new_prob, bins=[0, 0.33, 0.66, 1.0],
                         labels=['Low', 'Medium', 'High'], include_lowest=True)

# Combine predictions with features and EmployeeID
new_df_results = pd.concat([
    pd.DataFrame({
        'EmployeeID': new_df['EmployeeID'],
        'Predicted': new_pred,
        'Probability': new_prob,
        'Risk Level': risk_levels_new
    }),
    X_new.reset_index(drop=True)
], axis=1)

# Add suggested strategies
new_df_results['Suggested_Strategies'] = new_df_results.apply(
    lambda row: get_strategies(row) if row['Risk Level'] in ['Medium', 'High']
    else 'Low risk - Monitor generally.',
    axis=1
)

print(new_df_results.head()[''])

Accuracy: 0.8741496598639455
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.98      0.93       255
           1       0.60      0.15      0.24        39

    accuracy                           0.87       294
   macro avg       0.74      0.57      0.59       294
weighted avg       0.85      0.87      0.84       294


Sample Predictions with Strategies:
    Actual  Predicted  Probability Risk Level  Age  DailyRate  \
0       0          0         0.13        Low   28        866
1       0          0         0.06        Low   53       1084
2       1          1         0.53     Medium   24        240
3       0          0         0.03        Low   45       1339
4       0          0         0.06        Low   36       1396
5       0          1         0.54     Medium   34        204
6       0          0         0.16        Low   35        144
7       0          0         0.10        Low   39       1431
8       0          0         0.21        Low   45       1052
9       0          0         0.18        Low   35       1229

   DistanceFromHome  EnvironmentSatisfaction  JobInvolvement  JobLevel  ...  \
0                 5                        4               3         2  ...
1                13                        4               4         2  ...
2                22                        4               1         1  ...
3                 7                        2               3         3  ...
4                 5                        4               3         2  ...
5                14                        3               3         1  ...
6                22                        4               1         1  ...
7                 1                        3               3         1  ...
8                 6                        4               2         3  ...
9                 8                        4               4         1  ...

   YearsAtCompany  YearsInCurrentRole  YearsWithCurrManager  BusinessTravel  \
0               5                   4                     3   Travel_Rarely
1               4                   2                     3   Travel_Rarely
2               1                   0                     0   Travel_Rarely
3               1                   0                     0   Travel_Rarely
4              13                  11                     7   Travel_Rarely
5               8                   2                     6   Travel_Rarely
6               5                   4                     3   Travel_Rarely
7               3                   2                     2   Travel_Rarely
8              19                   7                     8      Non-Travel
9               1                   0                     1   Travel_Rarely

               Department    EducationField                 JobRole  \
0                   Sales           Medical         Sales Executive
1  Research & Development           Medical  Manufacturing Director
2         Human Resources   Human Resources         Human Resources
3  Research & Development     Life Sciences      Research Scientist
4  Research & Development     Life Sciences   Laboratory Technician
5                   Sales  Technical Degree    Sales Representative
6  Research & Development     Life Sciences   Laboratory Technician
7  Research & Development           Medical   Laboratory Technician
8                   Sales           Medical         Sales Executive
9  Research & Development     Life Sciences   Laboratory Technician

   MaritalStatus  OverTime                               Suggested_Strategies
0         Single        No                      Low risk - Monitor generally.
1       Divorced        No                      Low risk - Monitor generally.
2        Married        No  MonthlyIncome: Offer competitive salary review...
3       Divorced        No                      Low risk - Monitor generally.
4         Single        No                      Low risk - Monitor generally.
5       Divorced       Yes  OverTime: Implement overtime caps, flexible sc...
6         Single        No                      Low risk - Monitor generally.
7       Divorced        No                      Low risk - Monitor generally.
8         Single        No                      Low risk - Monitor generally.
9        Married        No                      Low risk - Monitor generally.

[10 rows x 26 columns]
   EmployeeID  Predicted  Probability Risk Level  Age  DailyRate  \
0           1          1         0.78       High   41       1102
1           2          0         0.00        Low   49        279
2           3          1         0.83       High   37       1373
3           4          0         0.17        Low   33       1392
4           5          0         0.00        Low   27        591

   DistanceFromHome  EnvironmentSatisfaction  JobInvolvement  JobLevel  ...  \
0                 1                        2               3         2  ...
1                 8                        3               2         2  ...
2                 2                        4               2         1  ...
3                 3                        4               3         1  ...
4                 2                        1               3         1  ...

   YearsAtCompany  YearsInCurrentRole  YearsWithCurrManager  \
0               6                   4                     5
1              10                   7                     7
2               0                   0                     0
3               8                   7                     0
4               2                   2                     2

      BusinessTravel              Department  EducationField  \
0      Travel_Rarely                   Sales   Life Sciences
1  Travel_Frequently  Research & Development   Life Sciences
2      Travel_Rarely  Research & Development           Other
3  Travel_Frequently  Research & Development   Life Sciences
4      Travel_Rarely  Research & Development         Medical

                 JobRole  MaritalStatus  OverTime  \
0        Sales Executive         Single       Yes
1     Research Scientist        Married        No
2  Laboratory Technician         Single       Yes
3     Research Scientist        Married       Yes
4  Laboratory Technician        Married        No

                                Suggested_Strategies
0  OverTime: Implement overtime caps, flexible sc...
1                      Low risk - Monitor generally.
2  OverTime: Implement overtime caps, flexible sc...
3                      Low risk - Monitor generally.
4                      Low risk - Monitor generally.

[5 rows x 26 columns]